# Generated by Django 5.0.7 on 2024-08-07 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='Video_file',
            new_name='video_file',
        ),
    ]
